name: CI Data Pipeline

# 1. Déclenchement du pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  # JOB 1 : Vérifier l'infrastructure (Terraform)
  terraform-check:
    name: Validate Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  # JOB 2 : Vérifier le code Data (Notebooks PySpark)
  notebook-lint:
    name: Lint PySpark Notebooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installer les outils (nbqa et flake8)
        run: pip install nbqa flake8

      - name: Vérifier la syntaxe des Notebooks (.ipynb)
        run: nbqa flake8 . --select=E9,F63,F7,F82 --show-source